from .batch_video_loader import (
    NODE_CLASS_MAPPINGS as _LOADER_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _LOADER_NAMES,
)
from .ensure_even_dimensions import (
    NODE_CLASS_MAPPINGS as _EVEN_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _EVEN_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LOADER_CLASSES, **_EVEN_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LOADER_NAMES, **_EVEN_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
